# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # JDK version
      - image: circleci/openjdk:8-jdk

    # Directory where the below steps are run
    working_directory: ~/ESDAssignment/XYZDriverAssociation

    environment:
      # JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:

      # Checkout the branch into the working_directory root
      - checkout:
          path: ~/ESDAssignment

      - setup_remote_docker

      - run:
          name: update
          command: ssh remote-docker \
            sudo apt-get update
      - run:
          name: upgrade
          command: ssh remote-docker \
            sudo apt-get upgrade
      - run:
          name: Download
          command: ssh remote-docker \
            sudo wget http://download.oracle.com/glassfish/5.0/release/glassfish-5.0.zip -P /bin/
      - run:
          name: Unzip and Delete
          command: ssh remote-docker \
            sudo unzip /bin/glassfish-5.0.zip -d /bin/ && sudo rm -rf /bin/glassfish-5.0.zip
      - run:
          name: Start
          command: ssh remote-docker \
            sudo bin/glassfish5/bin/asadmin start-domain

      # Restore previously cached dependencies if a cache exists
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Download latest dependencies
      - run: mvn dependency:go-offline

      # Cache the dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Run unit tests
      - run: mvn test
